from flask import Flask, request, send_file
from pptx import Presentation
from pptx.util import Inches

app = Flask(__name__)

@app.route("/")
def home():
    return "PowerPoint Generator API is Running - by Simra"

@app.route("/generate", methods=["POST"])
def generate_ppt():
    data = request.json
    title = data.get("title", "My Presentation")
    slides_data = data.get("slides", ["Slide 1 Content", "Slide 2 Content"])

    prs = Presentation()
    # Title Slide
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    slide.shapes.title.text = title
    slide.placeholders[1].text = "Generated by Simra's API"

    # Content Slides
    for content in slides_data:
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        slide.shapes.title.text = content[:30]
        slide.placeholders[1].text = content

    prs.save("output.pptx")
    return send_file("output.pptx", as_attachment=True)

if __name__ == "__main__":
    app.run(debug=True)
